### ISSUE TITLE
Callback fired 6 times

### ISSUE THREAD

**Issue by TheTimmaeh** [enhancv/popup-tools#2]
Hey there,

usually when I close the window myself, the callback gets fired 6 times. Usually when the window gets closed by res.end(popupTools.popupResponse(...)) I don't have that issue, but there's no guarantee for that. And occasionally the callback gets fired when nothing is done.

I've coded my own working solution, but wanted to reach out so that bug can get fixed.

Tested in Chrome 58 on Windows 10 running node v6.10.3

**Comment by sureshdmavericks** [comment]
I'm having the same issue. How can it be solved?
