### ISSUE TITLE
Popup is not getting closed and spits out the response html in string

### ISSUE THREAD

**Issue by prem911** [enhancv/popup-tools#5]
In my dev environment, where NODE_ENV is set to development, this works like a charm.
But when NODE_ENV is set to production, I see that the popup is not closing.

I see this script in the popup window
window.opener.postMessage({"status":true,"message":"Google Auth successful"}, "*");setTimeout(function() { window.close(); }, 50);

I have responded with the json from the server.
When I open the developer console for the popup window and then run this script in the console, then the window closes and the post close of popup call is executed.

Any pointers what could be going wrong?

**Comment by prem911** [comment]
Found the fix.
We need to set the content type to text/html.
If we dont set it then it takes the script as a string and hence doesnot execute it.
Kindly update this in the documentation.

```js
router.get('/auth/google/callback',
  passport.authenticate('google'), 
    function (req, res) {
      res.set('Content-Type', 'text/html');  /* THIS IS IMPORTANT */
      res.end(popupTools.popupResponse({status: true, message: 'Google Auth successful'}));
  },
  function(err,req,res,next) {
    if(err) {
      res.set('Content-Type', 'text/javascript');
      res.end(popupTools.popupResponse({status: false, message: err.message}));
    }
  }  
);
```

**Comment by ivank** [comment]
Wow, 10x a lot @prem911 I'll update the docs right away!

**Comment by prem911** [comment]
@ivank This is best example of community development. Thanks for this lovely utility.
